FROM almalinux:9
ADD https://raw.githubusercontent.com/saipavan4572/shell-script/refs/heads/main/ansible.MD /tmp/add/ansible.MD
# ADD: it is going to download and add the file from the internet
ADD expenses-documentation.tar /tmp/
# .tar file will untar and place the content under /tmp folder
CMD [ "sleep","100" ]
